name: juntos_app
description: none
version: 1.0.0+11 # Dev: 1.0.0+11 / Prod: 1.0.3+8
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Added
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.2 # https://pub.dev/packages/bloc
  cached_network_image: ^3.3.0 # https://pub.dev/packages/cached_network_image
  carousel_slider: ^4.2.1 # https://pub.dev/packages/carousel_slider
  connectivity_plus: ^5.0.0 # https://pub.dev/packages/connectivity_plus
  cupertino_icons: ^1.0.6 # https://pub.dev/packages/cupertino_icons
  dartz: ^0.10.1 # https://pub.dev/packages/dartz
  dio: ^5.4.2+1 # https://pub.dev/packages/dio
  equatable: ^2.0.5 # https://pub.dev/packages/equatable
  file_picker: ^6.0.0 # https://pub.dev/packages/file_picker
  flutter_bloc: ^8.1.3 # https://pub.dev/packages/flutter_bloc
  flutter_form_builder: ^9.1.1 # https://pub.dev/packages/flutter_form_builder
  flutter_launcher_icons: ^0.13.1 # https://pub.dev/packages/flutter_launcher_icons
  flutter_native_splash: ^2.3.3 # https://pub.dev/packages/flutter_native_splash
  flutter_svg: ^2.0.7 # https://pub.dev/packages/flutter_svg
  flutter_screenutil: ^5.9.0 # https://pub.dev/packages/flutter_screenutil
  form_builder_validators: ^9.1.0 # https://pub.dev/packages/form_builder_validators
  get_it: ^7.6.4 # https://pub.dev/packages/get_it
  go_router: ^12.0.0 # https://pub.dev/packages/go_router
  intl: ^0.18.1 # https://pub.dev/packages/intl
  path_provider: ^2.1.1 # https://pub.dev/packages/path_provider
  screenshot: ^2.1.0 # https://pub.dev/packages/screenshot 
  share_plus: ^7.1.0 # https://pub.dev/packages/share_plus
  shared_preferences: ^2.2.2 # https://pub.dev/packages/shared_preferences
  url_launcher: ^6.1.14 # https://pub.dev/packages/url_launcher
  video_player: ^2.8.1 # https://pub.dev/packages/video_player

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  # Added
  assets:
    - assets/images/
    - assets/svg/

# Added
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
