import 'dart:developer';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';
import 'package:form_builder_validators/form_builder_validators.dart';
import 'package:go_router/go_router.dart';
import 'package:juntos_app/app/core/theme/theme.dart';
import 'package:juntos_app/app/core/utils/utils.dart';
import 'package:juntos_app/app/features/home/domain/entities/entities.dart'
    as entity;
import 'package:juntos_app/l10n/l10n.dart';

part 'custom_app_bar.dart';
part 'custom_bottom_sheet.dart';
part 'custom_button.dart';
part 'custom_carousel.dart';
part 'custom_continue_button.dart';
part 'custom_empty.dart';
part 'custom_error.dart';
part 'custom_flavor_banner.dart';
part 'custom_icon.dart';
part 'custom_image_animation.dart';
part 'custom_image_asset.dart';
part 'custom_image_avatar.dart';
part 'custom_image_logo.dart';
part 'custom_image_network.dart';
part 'custom_progress.dart';
part 'custom_radio_group.dart';
part 'custom_scroll_behavior.dart';
part 'custom_slide_transition.dart';
part 'custom_text_field.dart';
part 'custom_text.dart';
